on: workflow_dispatch
name: ğŸš€ Deploy website on demand
jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v2
    
    - name: ğŸ”¨ Build website
      uses: helaili/jekyll-action@v2
      with:
        build_only: true

    - name: ğŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        local-dir: build/
        state-name: ../.sync-state.json
        server: ftp.amanaska.org
        username: website_upload2@amanaska.org	
        password: ${{ secrets.ftp_password }}
